In [1]:
import pandas as pd
import requests
import numpy as np
from io import StringIO
import datetime

In [49]:
class TwStock:
#     對照表
    m_mapping = {'上市':'sii','上櫃':'otc'}
    base_url = 'https://mops.twse.com.tw/mops/web/'
    p_mapping = {'損益表':base_url+'t163sb04'
                ,'資產負債表':base_url+'t163sb05'
                ,'營益分析':base_url+'t163sb06'
                ,'財務結構分析':base_url+'t51sb02'}
    old_p_mapping = {'損益表':base_url+'t51sb08'
                ,'資產負債表':base_url+'t51sb07'
                ,'營益分析':base_url+'t51sb06'
                ,'財務結構分析':base_url+'t51sb02'}

    def __init__(self, year, season, mkt_type, purpose, \
                 filter_ind=True, m_mapping=m_mapping, p_mapping=p_mapping, old_p_mapping=old_p_mapping):
        year = year if year < 1000 else year-1911
        self.year = year
        self.season = '0'+str(season)
        self.mkt_type = m_mapping[mkt_type] if mkt_type in m_mapping else None
        self.purpose = purpose
        p_mapping = p_mapping if self.year>=102 else old_p_mapping
        self.url = p_mapping[self.purpose] if self.purpose in p_mapping else None
        self.filter_ind=filter_ind
    
    def add_raw(self):
        form = {'encodeURIComponent':1,
            'step':1,
            'firstin':1,
            'off':1,
            'TYPEK':self.mkt_type,
            'year':self.year,
            'season':self.season,
            'ifrs':'Y'
            }
        headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) \
                AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
            
        r = requests.post(self.url, form, headers=headers)
        r.encoding = 'utf8'
        dfs = pd.read_html(StringIO(r.text))
        self.raw_data = dfs
        
#     損益表
    def unify_incm(self):
        self.dfs = [i for i in self.raw_data if '公司代號' in i.columns]
        self.dfs = [self.dfs[1], self.dfs[2]] if self.filter_ind==True else self.dfs
#         self.dfs = [i for i in self.dfs if '央行及金融同業存款' not in i.columns] \
#         if self.filter_ind==True else self.dfs
        self.dfs[0].rename(columns={'收益':'營業收入',
                          '營業利益':'營業利益(損失)',
                          '稅前淨利（淨損）':'稅前淨利(淨損)',
                          '本期淨利（淨損）':'本期淨利(淨損)'}, inplace=True)
        self.dfs[1].rename(columns={'營業利益（損失）':'營業利益(損失)',
                          '稅前淨利（淨損）':'稅前淨利(淨損)',
                          '本期淨利（淨損）':'本期淨利(淨損)'}, inplace=True)
        for i in self.dfs:
            i.rename(columns={'基本每股盈餘（元）':'EPS'}, inplace=True)
        self.dfs = [i[['公司代號', '公司名稱', '營業收入', '營業利益(損失)', '稅前淨利(淨損)', '本期淨利(淨損)', \
                  'EPS']] for i in self.dfs]
        df_all = pd.concat(self.dfs, ignore_index=True)
        self.data = df_all
        
#     資產負債表
    def unify_baln(self):
        self.dfs = [i for i in self.raw_data if '公司代號' in i.columns]
        self.dfs = [i for i in self.dfs if '央行及金融同業存款' not in i.columns] \
            if self.filter_ind==True else self.dfs
        self.dfs[0].rename(columns={'保留盈餘（或累積虧損）':'保留盈餘'
                  ,'資產合計':'資產總額'
                  ,'負債合計':'負債總額'
                  ,'權益合計':'權益總額'}, inplace=True)
        imp = ['公司代號', '公司名稱', '流動資產', '非流動資產', '資產總額', '流動負債', '非流動負債', '負債總額', '股本',
            '資本公積', '保留盈餘', '其他權益', '庫藏股票', '權益總額', '每股參考淨值']
        self.dfs = [i[imp] for i in self.dfs]   
        df_all = pd.concat(self.dfs, ignore_index=True)
        df_all = df_all[df_all['公司代號']!='公司代號']
        self.data = df_all
        
#     營益分析
    def unify_incm_ratio(self):
        dfs = [i for i in x.raw_data if len(i)>0]
        dfs = [i for i in dfs if i.iloc[0][0]=='公司代號']
        data = dfs[0]
        data.columns = list(dfs[0].iloc[0])
        data = data[data['公司代號']!='公司代號']
        data.rename(columns={'毛利率(%)(營業毛利)/(營業收入)':'毛利率(%)'
                     ,'營業利益率(%)(營業利益)/(營業收入)':'營業利益率(%)'
                     ,'稅前純益率(%)(稅前純益)/(營業收入)':'稅前純益率(%)'
                     ,'稅後純益率(%)(稅後純益)/(營業收入)':'稅後純益率(%)'}, inplace=True)
        data = data.reset_index().drop('index', axis=1)
        self.data = data

#     財務結構分析
    def unify_baln_ratio(self, smp=True):
        dfs = [i for i in x.raw_data if i.shape[1]>15]
        data = dfs[0]
        data.columns = data.columns.get_level_values(1)
        data = data[data['公司代號']!='公司代號']
        data = data.reset_index().drop('index', axis=1)
        if smp==True :
            clms = list(data.columns)
            clms = [i for i in clms if i not in \
                   ['長期資金佔不動產、廠房及設備比率(%)', '不動產、廠房及設備週轉率(次)'
                    , '平均收現日數', '純益率(%)', '平均銷貨日數', '稅前純益佔實收資本比率(%)']]
            data = data[clms]
            data.rename(columns={'負債佔資產比率(%)':'負債比率(%)'}, inplace=True)
        self.data = data

# ifrs後

$ 上市 / 損益表 $

In [50]:
x = TwStock(2015, 1, '上市', '損益表')

In [51]:
x.add_raw()

In [52]:
x.unify_incm()

In [54]:
x.data.head()

   公司代號 公司名稱      營業收入  營業利益(損失)  稅前淨利(淨損)  本期淨利(淨損)   EPS
0  2855  統一證   1131274     45846    645816    558741  0.42
1  6005  群益證   1644903    419747    681728    590506  0.24
2  6024  群益期    198086    -88102     70877     57577  0.49
3  1101   台泥  21440142   1693508   1469867    974518  0.22
4  1102   亞泥  15362530   1037375   1844700   1542288  0.47

上櫃 / 損益表

In [174]:
x = TwStock(2015, 1, '上櫃', '損益表')
x.add_raw()

In [175]:
[i.shape for i in x.dfs]

[(6, 22), (665, 28), (1, 22), (1, 18)]

In [176]:
x.unify_col()

KeyError: "['Net_Income', 'Pre_Tax_Income', 'Operating_Income', 'Gross_Profit'] not in index"

In [178]:
[i.shape for i in x.dfs]

[(6, 22), (665, 28), (1, 22), (1, 18)]

# 財務比率分析

上市 / 營益分析

In [39]:
x = TwStock(2015, 1, '上市', '營益分析')
x.add_raw()

In [40]:
x.unify_incm_ratio()

In [41]:
x.data.head()

   公司代號 公司名稱 營業收入(百萬元)  毛利率(%) 營業利益率(%) 稅前純益率(%) 稅後純益率(%)
0  1101   台泥  21440.14   13.34     7.90     6.86     4.55
1  1102   亞泥  15362.53   10.62     6.75    12.01    10.04
2  1103   嘉泥    671.36  -11.27   -27.67   -31.21   -27.30
3  1104   環泥   1327.43    8.30     1.85    20.32    19.73
4  1108   幸福   1290.90   20.88    15.37    14.48    12.01

上櫃 / 營益分析

In [51]:
x = TwStock(2015, 1, '上櫃', '營益分析')
x.add_raw()

In [52]:
x.unify_incm_ratio()

In [53]:
x.data.head()

   公司代號   公司名稱 營業收入(百萬元) 毛利率(%) 營業利益率(%) 稅前純益率(%) 稅後純益率(%)
0  1258  其祥-KY    324.18  32.33    10.06    11.79     9.26
1  1259     安心   1053.39  25.79     1.75     2.16     1.51
2  1264     德麥    937.93  36.67    15.31    15.33    12.41
3  1333    恩得利    226.08  17.71    -3.56     2.64     1.81
4  1336     台翰    418.88   2.63   -10.71    -9.81    -8.17

上市 / 財務結構分析

In [63]:
x = TwStock(2015, 1, '上市', '財務結構分析')
x.add_raw()

In [64]:
x.unify_baln_ratio()

In [65]:
x.data.head()

,公司代號,公司簡稱,負債比率(%),流動比率(%),速動比率(%),利息保障倍數(%),應收款項週轉率(次),存貨週轉率(次),總資產週轉率(次),資產報酬率(%),權益報酬率(%),每股盈餘(元),現金流量比率(%),現金流量允當比率(%),現金再投資比率(%)
0,1101,台泥,46.95,133.06,119.28,6.07,4.01,8.15,0.32,2.85,4.36,1.56,31.97,109.73,3.19
1,1102,亞泥,42.66,81.02,69.80,5.14,3.55,7.08,0.24,2.28,3.12,1.55,20.95,112.25,2.97
2,1103,嘉泥,48.70,699.93,609.52,186.35,6.34,1.75,0.10,1.31,1.28,0.34,19.88,59.60,0.24
3,1104,環泥,19.88,123.51,103.82,101.84,4.26,13.93,0.26,7.09,8.70,2.22,34.43,59.18,1.09
4,1108,幸福,38.32,285.67,81.91,15.46,4.91,1.16,0.64,6.14,9.78,1.16,55.80,221.19,4.35

上櫃 / 財務結構分析

In [16]:
x = TwStock(2015, 1, '上櫃', '財務結構分析')
x.add_raw()

In [17]:
x.unify_baln_ratio()

In [18]:
x.data.head()

,公司代號,公司簡稱,負債佔資產比率(%),長期資金佔不動產、廠房及設備比率(%),流動比率(%),速動比率(%),利息保障倍數(%),應收款項週轉率(次),平均收現日數,存貨週轉率(次),...,不動產、廠房及設備週轉率(次),總資產週轉率(次),資產報酬率(%),權益報酬率(%),稅前純益佔實收資本比率(%),純益率(%),每股盈餘(元),現金流量比率(%),現金流量允當比率(%),現金再投資比率(%)
0,1258,其祥-KY,50.33,183.27,205.87,192.60,24.73,10.87,33.57,47.45,...,4.03,1.48,10.69,17.60,45.76,6.91,3.79,52.33,NaN,14.04
1,1259,安心,36.50,469.99,229.18,222.53,63061.00,80.98,4.50,73.13,...,11.38,1.75,3.41,5.27,38.93,1.95,4.05,42.80,127.72,0.09
2,1264,德麥,22.55,360.49,346.51,263.74,5465.08,4.75,76.84,5.29,...,6.52,1.47,16.71,22.01,175.90,11.19,13.33,70.76,103.33,5.29
3,1268,漢來美食,56.34,188.81,114.89,46.52,37.11,34.01,10.73,31.50,...,4.82,1.19,8.45,21.94,75.23,6.26,6.13,32.11,195.33,17.97
4,1333,恩得利,56.60,449.69,91.01,66.98,-0.02,2.30,158.69,5.27,...,7.95,0.72,-1.24,-6.76,-2.74,-4.00,-0.33,1.86,42.53,1.92

In [20]:
x.data.columns

Index(['公司代號', '公司簡稱', '負債佔資產比率(%)', '長期資金佔不動產、廠房及設備比率(%)', '流動比率(%)',
       '速動比率(%)', '利息保障倍數(%)', '應收款項週轉率(次)', '平均收現日數', '存貨週轉率(次)', '平均銷貨日數',
       '不動產、廠房及設備週轉率(次)', '總資產週轉率(次)', '資產報酬率(%)', '權益報酬率(%)',
       '稅前純益佔實收資本比率(%)', '純益率(%)', '每股盈餘(元)', '現金流量比率(%)', '現金流量允當比率(%)',
       '現金再投資比率(%)'],
      dtype='object')

# balance

In [28]:
r = requests.post('https://mops.twse.com.tw/mops/web/ajax_t51sb08', {
        'encodeURIComponent':1,
        'step':1,
        'firstin':1,
        'off':1,
        'TYPEK':'sii',
        'year':97,
        'season':'01',
    })
r.encoding = 'utf8'
dfs = pd.read_html(StringIO(r.text))

In [31]:
dfs

[                                                   0
 0               註：依證券交易法第36條及證券期貨局相關函令規定，財務報告申報期限如下：
 1  1.個別財務報表申報期限：年度為3月31日（101年申報100年度財務報告起適用），第一季為...
 2  2.合併財務報表申報期限：年度為3月31日（101年申報100年度財務報告起適用），第一季為...
 3                           3.申報期限如遇例假日，以證券期貨局公布者為準。
 4                                           單位：新台幣仟元,
      公司代號  公司名稱      營業收入      營業成本  營業毛利(毛損)  聯屬公司間未實現利益  聯屬公司間已實現利益  \
 0    1101    台泥   5959385   5558941    400444           0         307
 1    1102    亞泥   2638563   2148067    490496        9093           0
 2    1103    嘉泥    618302    537922     80380           0           0
 3    1104    環泥    699474    650364     49110           0           0
 4    1108    幸福    807109    705057    102052           0           0
 5    1109    信大    456279    355626    100653         221         631
 6    1110    東泥    455435    381808     73627           0           0
 7    1201    味全   2404611   1522446    882165           0           0
 8    1203    味王    459238    321970    137268           0           0
 9    1210    大成   5470584   4960271    510313           0           0
 10   1213    大飲    146066    124341     21725           0           0
 11   1215    卜蜂   3243368   2908948    334420           0           0
 12   1216    統一  12247402   9730344   2517058           0           0
 13   1217   愛之味    980534    627100    353434       16043       15163
 14   1218    泰山   1597326   1442231    155095       11839       13004
 15   公司代號  公司名稱      營業收入      營業成本  營業毛利(毛損)  聯屬公司間未實現利益  聯屬公司間已實現利益
 16   1219    福壽   2414227   2145586    268641           0       -1823
 17   1220    台榮    697478    657862     39616           0           0
 18   1225   福懋油   2118444   1942795    175649         942           0
 19   1227    佳格   1864846   1068599    796247           0           0
 20   1229    聯華   1038873    869174    169699           0           0
 21   1231   聯華食   1051731    753749    297982           0           0
 22   1232   大統益   4065461   3725835    339626           0           0
 23   1233    天仁    466501    182891    283610           0           0
 24   1234    黑松    715633    536936    178697       16637       16877
 25   1235    興泰    139878    123107     16771           0           0
 26   1236    宏亞    570081    386291    183790           0         -11
 27   1301    台塑  49696573  42998322   6698251        4299           0
 28   1303    南亞  61564283  50163732  11400551        9339           0
 29   1304    台聚   3593589   2993554    600035        8791           0
 ..    ...   ...       ...       ...       ...         ...         ...
 684  9914   美利達   2379000   2093157    285843      -21463           0
 685  9917    中保   1458180    714509    743671           0           0
 686  9918   欣天然    712968    504872    208096           0           0
 687  公司代號  公司名稱      營業收入      營業成本  營業毛利(毛損)  聯屬公司間未實現利益  聯屬公司間已實現利益
 688  9919   康那香    801315    629752    171563       -2481         238
 689  9921    巨大   3492187   3041814    450373           0        1978
 690  9924    福興    771254    626695    144559           0           0
 691  9925    新保    848050    421173    426877           0           0
 692  9926    新海    570049    469954    100095           0           0
 693  9927    泰銘   2690266   2639572     50694           0           0
 694  9928    中視    474968    347753    127215           0           0
 695  9929    秋雨    236248    233409      2839           0           0
 696  9930  中聯資源   1047002    728631    318371           0           0
 697  9931    欣高    269286    223695     45591           0           0
 698  9933    中鼎   6306952   5976682    330270        -663           0
 699  9934    成霖    749225    589423    159802           0       44031
 700  9935   慶豐富   1146349   1035503    110846        3602        6504
 701  9937    全國   5430110   4878751    551359           0           0
 702  9938    百和    444449    334976    109473           0       -3065
 703  公司代號  公司名稱      營業收入      營業成本  營業毛利(毛損)  聯屬公司間未實現利益  聯屬公司間已實現利益
 704  9939    宏全   1013452    816269    197183           0          70
 705  9940    信義   1677539   1113581    563958           0           0
 706  9941    裕融    303381    128776    174605           0           0
 707  9942    茂順    415146    294891    120255        2958           0
 708  9943   好樂迪    875385    370251    505134           0           0
 709  9944    新麗    114790     93487     21303         608        3436
 710  9945   潤泰新   3112912   2539469    573443           0           0
 711  9946  三發地產     90728     38907     51821           0           0
 712  9955    佳龍   1161092   1036684    124408           0           0
 713  9958   世紀鋼    417893    372453     45440           0           0

         營業費用  營業淨利(淨損)  營業外收入及利益  營業外費用及損失  繼續營業單位稅前淨利(淨損)  所得稅(費用)利益  \
 0     292006    108745   1359336    170842         1297239      15000
 1     173171    308232   3242927    608425         2942734      79118
 2      50480     29900    359662    165996          223566        409
 3      90674    -41564    250173     23384          185225       -552
 4      66578     35474    109071     28255          116290      17239
 5      47266     53797     99848     10009          143636      15486
 6      23041     50586     55558     26321           79823       3641
 7     697050    185115     26935     73952          138098      17719
 8     113669     23599      8644     37414           -5171       6308
 9     251076    259237    233854     53015          440076      67464
 10     24262     -2537      6579      1833            2209        959
 11    169539    164881     17157     18486          163552      40011
 12   1923098    593960   1070479    390047         1274392      96776
 13    327870     24684     81376     78787           27273      -5874
 14    117324     38936     25588     38188           26336       -616
 15      營業費用  營業淨利(淨損)  營業外收入及利益  營業外費用及損失  繼續營業單位稅前淨利(淨損)  所得稅(費用)利益
 16    127742    139076     24438     26970          136544      34347
 17     28720     10896     29860     13207           27549       6824
 18     63788    110919     51912     19453          143378      30136
 19    389775    406472     65531     30385          441618     118789
 20     55680    114019     73794     10764          177049      31214
 21    255167     42815     22873     39263           26425       6607
 22     71600    268026     41322     97815          211533      48032
 23    220081     63529      2496      3869           62156       8200
 24    198351    -19414     63600      4133           40053       5949
 25     14044      2727     20814      4855           18686       2004
 26    104712     79067      4495      8006           75556      20345
 27   2158542   4535410   4300312    799685         8036037    1080558
 28   3491966   7899246   2671911   1861027         8710130     561930
 29    133574    457670    253522     54982          656210     140771
 ..       ...       ...       ...       ...             ...        ...
 684   114491    192815    269773    137741          324847      82890
 685   401210    342461    202009     21890          522580      83900
 686    49211    158885      5468     41225          123128      41763
 687     營業費用  營業淨利(淨損)  營業外收入及利益  營業外費用及損失  繼續營業單位稅前淨利(淨損)  所得稅(費用)利益
 688   136791     37491     50683     10268           77906      28785
 689   291272    161079    345008    157723          348364       7639
 690    86161     58398     25239     71519           12118       3459
 691   281719    145158    132804      9913          268049      39000
 692    33034     67061      8769       162           75668      19000
 693    35925     14769     74460     79265            9964       2306
 694   149330    -22115     13184     50278          -59209        -29
 695    22530    -19691      6845     19293          -32139      -1372
 696   144480    173891    304399      5436          472854      56022
 697    30544     15047     10979      2079           23947       5165
 698   167676    163257    357954     76594          444617      87840
 699   130175     73658    121335     56177          138816      -8406
 700    71254     42494      6373     84185          -35318      -6928
 701   463951     87408     69095     18719          137784      39867
 702   120365    -13957     91338     42060           35321      -6442
 703     營業費用  營業淨利(淨損)  營業外收入及利益  營業外費用及損失  繼續營業單位稅前淨利(淨損)  所得稅(費用)利益
 704    98025     99228     78680     26691          151217      34861
 705   156134    407824     66791     21298          453317     111750
 706   128209     46396     99480      2537          143339      10801
 707    50693     66604     28674      6943           88335      17995
 708   388993    116141     31367      9573          137935      30191
 709    20392      3739     43388     30625           16502      -5070
 710   390492    182951    244452     61242          366161       -798
 711    52239      -418      2407      3917           -1928          0
 712    22502    101906      9127     18244           92789      23313
 713    17051     28389      8391     17129           19651       3098

      繼續營業單位淨利(淨損)  停業單位損益  非常損益  會計原則變動累積影響數  合併前非屬共同控制股權損益  本期淨利(淨損)  基本每股盈餘
 0         1282239       0     0            0              0   1282239    0.39
 1         2863616       0     0            0              0   2863616    1.05
 2          223157       0     0            0              0    223157    0.41
 3          185777       0     0            0              0    185777    0.33
 4           99051       0     0            0              0     99051    0.24
 5          128150       0     0            0              0    128150    0.30
 6           76182       0     0            0              0     76182    0.13
 7          120379       0     0            0              0    120379    0.24
 8          -11479       0     0            0              0    -11479   -0.02
 9          372612       0     0            0              0    372612    0.96
 10           1250       0     0            0              0      1250    0.02
 11         123541       0     0            0              0    123541    0.53
 12        1177616       0     0            0              0   1177616    0.33
 13          33147       0     0            0              0     33147    0.09
 14          26952       0     0            0              0     26952    0.09
 15   繼續營業單位淨利(淨損)  停業單位損益  非常損益  會計原則變動累積影響數  合併前非屬共同控制股權損益  本期淨利(淨損)  基本每股盈餘
 16         102197       0     0            0              0    102197    0.38
 17          20725       0     0            0              0     20725    0.12
 18         113242       0     0            0              0    113242    0.70
 19         322829       0     0            0              0    322829    1.01
 20         145835       0     0            0              0    145835    0.20
 21          19818       0     0            0              0     19818    0.17
 22         163501       0     0            0              0    163501    1.02
 23          53956       0     0            0              0     53956    0.61
 24          34104       0     0            0              0     34104    0.06
 25          16682       0     0            0              0     16682    0.38
 26          55211       0     0            0              0     55211    0.68
 27        6955479       0     0            0              0   6955479    1.22
 28        8148200       0     0            0              0   8148200    1.07
 29         515439       0     0            0              0    515439    0.71
 ..            ...     ...   ...          ...            ...       ...     ...
 684        241957       0     0            0              0    241957    1.12
 685        438680       0     0            0              0    438680    1.01
 686         81365       0     0            0              0     81365    0.48
 687  繼續營業單位淨利(淨損)  停業單位損益  非常損益  會計原則變動累積影響數  合併前非屬共同控制股權損益  本期淨利(淨損)  基本每股盈餘
 688         49121       0     0            0              0     49121    0.25
 689        340725       0     0            0              0    340725    1.22
 690          8659       0     0            0              0      8659    0.05
 691        229049       0     0            0              0    229049    0.62
 692         56668       0     0            0              0     56668    0.48
 693          7658       0     0            0              0      7658    0.05
 694        -59180       0     0            0              0    -59180   -0.21
 695        -30767       0     0            0              0    -30767   -0.22
 696        416832       0     0            0              0    416832    1.91
 697         18782       0     0            0              0     18782    0.20
 698        356777       0     0            0              0    356777    0.58
 699        147222       0     0            0              0    147222    0.53
 700        -28390       0     0            0              0    -28390   -0.16
 701         97917       0     0            0              0     97917    0.32
 702         41763       0     0            0              0     41763    0.16
 703  繼續營業單位淨利(淨損)  停業單位損益  非常損益  會計原則變動累積影響數  合併前非屬共同控制股權損益  本期淨利(淨損)  基本每股盈餘
 704        116356       0     0            0              0    116356    0.61
 705        341567       0     0            0              0    341567    1.86
 706        132538       0     0            0              0    132538    0.56
 707         70340       0     0            0              0     70340    0.85
 708        107744       0     0            0              0    107744    0.59
 709         21572       0     0            0              0     21572    0.24
 710        366959       0     0            0              0    366959    0.49
 711         -1928       0     0            0              0     -1928   -0.06
 712         69476       0     0            0              0     69476    0.85
 713         16553       0     0            0              0     16553    0.20

 [714 rows x 20 columns],
    公司代號 公司名稱    利息淨收益  手續費淨收益  利息以外淨收益     呆帳費用     營業費用  繼續營業單位稅前淨利(淨損)  \
 0  2801   彰銀  4712017  781053  1978466  1889602  3002506         1798375
 1  2809  京城銀   726548   79910   134943   267800   465833          127858
 2  2812  台中銀  1386235  250219    51760   122604   804709          510682
 3  2820   華票   152937  160903   392998    25376   108039          412520
 4  2834  臺企銀  3455963  502690   331523   290052  2325254         1172180
 5  2836  高雄銀   513722  115791   -78974        0   462238          -27490
 6  2838  聯邦銀  1778937  325393    43853   217697  1375630          229463
 7  2845  遠東銀  1009107  399673   797823   638911  1039507          128512
 8  2849  安泰銀   778789  127737    28041   824274   636024         -653468

    所得稅(費用)利益  繼續營業單位稅後淨利(淨損)  停業單位損益(稅後)  非常損益(稅後)  會計原則變動之累積影響數(稅後)  \
 0    -468764         1329611           0         0                 0
 1      -2354          125504           0         0                 0
 2    -101306          409376           0         0                 0
 3     -28414          384106           0         0                 0
 4      -7443         1164737           0         0                 0
 5     -47559          -75049           0         0                 0
 6     -47636          181827           0         0                 0
 7      29000          157512           0         0                 0
 8    -280334         -933802           0         0                 0

    本期淨利(淨損)  每股盈餘
 0   1329611  0.24
 1    125504  0.12
 2    409376  0.31
 3    384106  0.23
 4   1164737  0.30
 5    -75049 -0.15
 6    181827  0.09
 7    157512  0.08
 8   -933802 -0.28  ,
    公司代號 公司名稱      營業收入      營業成本  營業毛利(毛損)    營業費用  營業利益(損失)  營業外收入及利益  \
 0  2816  旺旺保   5780289   5452201    328088  329934     -1846      8554
 1  2823   中壽  28275043  27743528    531515  333335    198180      3683
 2  2832   台產   3004700   2300246    704454  247132    457322        17
 3  2850   新產   7346765   6823998    522767  452892     69875     40221
 4  2851  中再保   3547646   3412932    134714   88657     46057         5
 5  2852  第一保   3062637   2569020    493617  210055    283562         4

    營業外費用及損失  繼續營業單位稅前純益(純損)  所得稅費用(利益)  繼續營業單位稅後純益(純損)  停業單位損益  非常損益  \
 0       736            5972       -743            6715       0     0
 1       627          201236          0          201236       0     0
 2      1312          456027      34164          421863       0     0
 3         4          110092      17546           92546       0     0
 4         0           46062      13422           32640       0     0
 5         0          283566      20800          262766       0     0

    會計原則變動之累積影響數  本期淨利（淨損）  調整項目  每股稅後盈餘(元)
 0             0      6715     0       0.03
 1             0    201236     0       0.18
 2             0    421863     0       1.33
 3             0     92546     0       0.31
 4             0     32640     0       0.06
 5             0    262766     0       0.93  ,
     公司代號 公司名稱     利息淨收益   利息以外淨收益       淨收益     呆帳費用  收回(提存)各項保險責任準備淨額  \
 0   2880  華南金   6722606   3943462  10666068  2001985           -263546
 1   2881  富邦金   7909128  42779545  50688673  1563818         -38085269
 2   2882  國泰金  23650646   8299639  31950285   352033         -29103303
 3   2883  開發金    735903   1145498   1881401    31957                 0
 4   2884  玉山金   2377694   1468014   3845708   751193                 0
 5   2885  元大金   2592971   3587461   6180432   241285                 0
 6   2886  兆豐金   7268358   1871465   9139823  2439599           -215882
 7   2887  台新金   8409696   4906427  13316123  3791239                 0
 8   2888  新光金  11495532   6177017  17672549   579997         -19671219
 9   2889  國票金    -35958    928340    892382    70888                 0
 10  2890  永豐金   4332143  -1672977   2659166  1449116                 0
 11  2891  中信金   7832091   8543417  16375508  3087545                 0
 12  2892  第一金   6119209   3980304  10099513   856657           -515634

         營業費用  繼續營業單位稅前合併淨利(淨損)  所得稅(費用)利益  繼續營業單位稅後合併淨利(淨損)  停業單位損益(稅後)  \
 0    4577585           3822952    -680039           3142913           0
 1    6851371           4188215    -706162           3482053           0
 2   13323181         -10828232    4850250          -5977982           0
 3    1307325            542119     -88386            453733           0
 4    2146212            948303    -122360            825943           0
 5    4112681           1826466    -121989           1704477           0
 6    4961618           1522724    -794024            728700           0
 7    7861681           1663203    -580945           1082258           0
 8    6888791          -9467458    2620272          -6847186           0
 9     528079            293415     -85784            207631           0
 10   4608016          -3397966    1430314          -1967652           0
 11   8265325           5022638     -31545           4991093           0
 12   4196594           4530628   -1104360           3426268           0

     非常損益(稅後)  會計原則變動之累積影響數(稅後)    合併總損益  合併總損益歸屬予母公司股東  合併總損益歸屬予少數股權  \
 0          0                 0  3142913        3142879            34
 1          0                 0  3482053        3374982        107071
 2          0                 0 -5977982       -5976002         -1980
 3          0                 0   453733         459300         -5567
 4          0                 0   825943         825943             0
 5          0                 0  1704477        1678921         25556
 6          0                 0   728700         725177          3523
 7          0                 0  1082258          -9668       1091926
 8          0                 0 -6847186       -6861737         14551
 9         58                 0   207689         273562        -65873
 10         0                 0 -1967652       -1966791          -861
 11         0            -65296  4925797        4924804           993

In [30]:
def raw_baln(year, season, mkt_type='sii'):
    url = 'https://mops.twse.com.tw/mops/web/t163sb05'
    r = requests.post(url, {
            'encodeURIComponent':1,
            'step':1,
            'firstin':1,
            'off':1,
            'TYPEK':mkt_type,
            'year':year,
            'season':season,
        })
    r.encoding = 'utf8'
    return r.text

In [71]:
dfs = pd.read_html(raw_baln(103, 4))

In [72]:
dfs = [i for i in dfs if i.shape[1] > 15]

In [73]:
[i.shape for i in dfs]

[(11, 53), (3, 21), (855, 22), (14, 54), (7, 46), (4, 21)]

In [48]:
dfs = [i for i in dfs if (i.shape[1] > 15) & (i.shape[1] < 30)]

In [67]:
dfs[0].rename(columns={'保留盈餘（或累積虧損）':'保留盈餘'
                      ,'資產合計':'資產總額'
                      ,'負債合計':'負債總額'
                      ,'權益合計':'權益總額'}, inplace=True)

In [68]:
set.intersection(*map(set,[list(i) for i in dfs]))

{'保留盈餘',
 '公司代號',
 '公司名稱',
 '共同控制下前手權益',
 '其他權益',
 '庫藏股票',
 '待註銷股本股數（單位：股）',
 '權益總額',
 '每股參考淨值',
 '流動負債',
 '流動資產',
 '股本',
 '負債總額',
 '資本公積',
 '資產總額',
 '非流動負債',
 '非流動資產',
 '預收股款（權益項下）之約當發行股數（單位：股）'}

In [70]:
imp = ['公司代號', '公司名稱', '流動資產', '非流動資產', '資產總額', '流動負債', '非流動負債', '負債總額', '股本',
        '資本公積', '保留盈餘', '其他權益', '庫藏股票', '權益總額', '每股參考淨值']

In [71]:
dfs = [i[imp] for i in dfs]

In [73]:
def unify_baln(x):
    dfs = x.copy()
    dfs[0].rename(columns={'保留盈餘（或累積虧損）':'保留盈餘'
                      ,'資產合計':'資產總額'
                      ,'負債合計':'負債總額'
                      ,'權益合計':'權益總額'}, inplace=True)
    imp = ['公司代號', '公司名稱', '流動資產', '非流動資產', '資產總額', '流動負債', '非流動負債', '負債總額', '股本',
        '資本公積', '保留盈餘', '其他權益', '庫藏股票', '權益總額', '每股參考淨值']
    dfs = [i[imp] for i in dfs]   
    df_all = pd.concat(dfs, ignore_index=True)
    return df_all

In [74]:
df_all = unify_baln(dfs)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [78]:
def get_baln(year, season):
    year = year if year < 1000 else year-1911
#     if year >= 1000:
#         year -= 1911
    dfs = pd.read_html(raw_baln(year, season))
    dfs = [i for i in dfs if (i.shape[1] > 15) & (i.shape[1] < 30)]
    # 將不同欄位名統一
    df_all = unify_baln(dfs)    
    return df_all

In [77]:
year = 1111111111
year = year if year < 1000 else year-1911
print(year)

1111109200

In [79]:
get_baln(103, 4)

,公司代號,公司名稱,流動資產,非流動資產,資產總額,流動負債,非流動負債,負債總額,股本,資本公積,保留盈餘,其他權益,庫藏股票,權益總額,每股參考淨值
0,2855,統一證,59972212,4975334,64947546,41811986,60084,41872070,13231191,256116,9431778,113539,--,23075476,17.41
1,6005,群益證,69531529,14156814,83688343,49996260,1489963,51486223,23690730,2711760,4598641,97349,0,32202120,13.13
2,6024,群益期,14958003,476365,15434368,12730741,11195,12741936,1199979,377709,1062107,52637,0,2692432,22.44
3,1101,台泥,96605816,196138016,292743832,68632044,62094107,130726151,36921759,12225528,49530227,19281356,--,162017681,31.95
4,1102,亞泥,70558875,212260180,282819055,64989203,56102626,121091829,33614472,1073920,94863921,12281251,--,161727226,42.19
5,1103,嘉泥,12878015,20788464,33666479,3366245,11018176,14384421,7768285,570096,8390425,1774583,-1149426,19282058,26.88
6,1104,環泥,2652681,16730075,19382756,2068617,1516169,3584786,6159697,28999,7993017,1460564,--,15797970,25.39
7,1108,幸福,5561570,2801709,8363279,2333817,1414348,3748165,4047380,0,508990,28252,0,4615114,11.33
8,1109,信大,2767192,6516323,9283515,1840346,411048,2251394,4210008,22299,1568770,167234,0,7032121,14.18
9,1110,東泥,1788502,7814235,9602737,294502,448910,743412,5720008,184916,1983703,948426,-12185,8859325,15.49
10,1201,味全,21763676,17426392,39190068,22307990,5837004,28144994,5060629,688,2439217,327685,--,11045074,15.47
11,1203,味王,3275589,5034962,8310551,1452616,1708041,3160657,2400000,112965,1660939,147574,-38464,5149894,18.02
12,1210,大成,22293725,19101412,41395137,16389411,5061327,21450738,7363944,2377966,2992074,1370880,-306199,19944399,20.19
13,1213,大飲,379143,426326,805469,105356,37844,143200,514751,21938,125876,-296,--,662269,12.87
14,1215,卜蜂,4294343,5081589,9375932,3177367,841139,4018506,2436282,967,1320624,1486710,--,5357426,21.53
15,1216,統一,137311309,262432410,399743719,143379331,106762845,250142176,54634763,3848490,28951457,4577230,--,149601543,16.84
16,1217,愛之味,3109159,10564669,13673828,3662857,3791690,7454547,4976893,335464,188804,-59423,-100582,6219281,10.96
17,1218,泰山,2696076,5079584,7775660,2342356,2058609,4400965,3533360,23770,20044,-3353,-203876,3374695,9.92
18,1219,福壽,3542023,2767769,6309792,1053720,1312006,2365726,3131882,36696,619415,3150,--,3944066,12.10
19,1220,台榮,2190083,1074908,3264991,758008,290806,1048814,1770779,537,387971,-62686,0,2216177,11.84
20,1225,福懋油,3353705,3047219,6400924,1822617,1643865,3466482,2187030,121015,305157,15374,--,2934442,12.02
21,1227,佳格,13501577,4639772,18141349,5659720,378442,6038162,7206338,51331,4232457,486538,-21182,12103187,16.71
22,1229,聯華,2746474,23173919,25920393,3101234,1135291,4236525,8545383,715041,8790061,3584137,-2393,21683868,25.32
23,1231,聯華食,2739235,3418683,6157918,1786588,1757227,3543815,1481131,72435,991970,52152,--,2614103,17.54
24,1232,大統益,4288810,607700,4896510,1214893,104788,1319681,1599749,23784,1914220,-222,--,3576829,22.11
25,1233,天仁,772829,1211236,1984065,407170,124679,531849,905919,56075,514579,-38122,-2754,1452216,15.86
26,1234,黑松,6776557,14705101,21481658,1435688,2676371,4112059,4018711,184583,13042786,123519,0,17369599,43.22
27,1235,興泰,1817638,626489,2444127,1111472,64713,1176185,561688,41515,230415,444135,-9953,1267942,23.33
28,1236,宏亞,879899,2302725,3182624,659422,674805,1334227,1083425,33396,462336,269240,0,1848397,17.06
29,1256,鮮活果汁-KY,898716,509544,1408260,522613,63515,586128,246960,60109,456456,55804,--,822132,33.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,9918,欣天然,2389395,1617151,4006546,743453,435660,1179113,1805375,50646,972619,45621,-46828,2827433,15.88
833,9919,康那香,2963238,4042293,7005531,1690482,1889827,3580309,1971268,174922,725147,174443,--,3425222,15.45
834,9921,巨大,34856261,10318144,45174405,23261149,2371529,25632678,3750646,1720831,13569036,337263,0,19541727,51.67
835,9924,福興,3557896,3335148,6893044,1768980,424963,2193943,1884521,567114,1858272,281811,--,4699101,24.37
836,9925,新保,8819641,6679977,15499618,5079985,866351,5946336,3836530,146302,3852151,1013843,-39521,9553282,23.16
837,9926,新海,2329595,2505084,4834679,1365176,864819,2229995,1667634,--,733774,203276,--,2604684,15.62
838,9927,泰銘,5450515,1252601,6703116,1811900,239158,2051058,2091482,975330,1738594,-177768,--,4652058,22.13
839,9928,中視,615847,3995586,4611433,2816228,783613,3599841,1327246,2420,-340784,24070,-1482,1011592,7.62
840,9929,秋雨,419528,1502008,1921536,1012895,354412,1367307,1491704,15254,-942359,15832,0,554229,3.89
841,9930,中聯資源,1928291,4505430,6433721,1291894,458109,1750003,2259458,162026,2048242,86636,0,4683718,20.17
842,9931,欣高,936395,2488796,3425191,1290615,514627,1805242,1022505,30101,522352,21262,--,1619949,15.61
843,9933,中鼎,42090608,14747693,56838301,31033931,6101361,37135292,7575303,3230033,6093652,250563,-11835,19703009,22.66
844,9934,成霖,11936404,4931243,16867647,7123239,2841379,9964618,3543042,916938,2111138,231737,0,6903029,19.20
845,9935,慶豐富,1492117,1984308,3476425,2128564,466648,2595212,1381008,307312,-798755,-11191,--,881213,6.26
846,9937,全國,1153213,6838751,7991964,3679247,49324,3728571,3090430,18969,1176885,-22891,--,4263393,13.80
847,9938,百和,7272347,7086719,14359066,3278717,2288770,5567487,2979639,728388,2705068,332613,--,8791579,22.64
848,9939,宏全,7951069,21245897,29196966,11309968,6217608,17527576,2598479,3283868,4446978,294156,--,11669390,40.88
849,9940,信義,10704792,7101112,17805904,2877902,5411894,8289796,6134367,63896,2632205,546145,--,9516108,15.29
850,9941,裕融,66785130,18345222,85130352,74280720,1197238,75477958,2621581,1944337,4129343,146668,--,9652394,33.90
851,9942,茂順,2362410,1466827,3829237,573515,623535,1197050,831613,214743,1536719,51269,--,2632187,31.68
852,9943,好樂迪,1382954,2688742,4071696,523481,256173,779654,1473176,--,1808756,10110,--,3292042,22.35
853,9944,新麗,2493635,2756961,5250596,1645684,551294,2196978,1057964,184416,1456386,248819,0,3053618,27.86
854,9945,潤泰新,27507818,72872230,100380048,21201899,23634624,44836523,11925647,12716267,37734516,-10541569,-105200,55543525,43.55
855,9946,三發地產,11967927,458619,12426546,8380251,718062,9098313,2062027,405393,860813,--,0,3328233,16.14
856,9955,佳龍,1715142,2024840,3739982,499498,894629,1394127,1032082,1109441,188394,15686,0,2345855,22.73
857,9958,世紀鋼,3909149,2260595,6169744,1222455,2729380,3951835,1819197,69707,322368,6637,0,2217909,12.19
858,1409,新纖,91258194,38958768,130216962,84477565,11270027,95747592,16634613,1475689,6425862,1406520,-63086,34469370,15.64
859,1718,中纖,508001164,50535799,558536963,488402305,22857357,511259662,13716932,1457759,6318917,-254603,-1165133,47277301,17.77
860,2514,龍邦,85231931,428533998,513765929,5801970,491014052,496816022,5632143,309863,2853547,-1580262,-398159,16949907,13.13
861,2905,三商,149227232,670619592,819846824,17606258,774415265,792021523,6813689,897836,5482195,-720945,-532672,27825301,18.60